"use client";
import {useEffect,useRef,useState} from 'react';
import type {Coordinates,DestinationConstraint} from '@/src/types/domain';
import type {CombinedMatch,CombinedSchool} from '@/src/lib/data/combined';
export function CombinedMatches({destinations,center,minimumPrice,maximumPrice,onMatches,onSelect}:{destinations:DestinationConstraint[];center?:Coordinates;minimumPrice:number;maximumPrice:number;onMatches:(matches:CombinedMatch[])=>void;onSelect:(match:CombinedMatch)=>void}){
 const [school,setSchool]=useState<CombinedSchool>({enabled:false,phase:'Primary',rating:'all',reportArea:'Achievement',maximumWalkMinutes:15});
 const [result,setResult]=useState<{matches:CombinedMatch[];note:string;priceFailures:number;routeFailures:number}>();const [loading,setLoading]=useState(false);const [error,setError]=useState<string>();const controller=useRef<AbortController|null>(null);
 const identity=JSON.stringify({destinations,center,minimumPrice,maximumPrice,school});
 useEffect(()=>{controller.current?.abort();onMatches([]);return()=>controller.current?.abort();},[identity,onMatches]);
 const [resultIdentity,setResultIdentity]=useState('');
 const current=resultIdentity===identity;
 async function search(){controller.current?.abort();const active=new AbortController();controller.current=active;setLoading(true);setError(undefined);setResultIdentity(identity);setResult(undefined);onMatches([]);
  try{const response=await fetch('/api/matches',{method:'POST',signal:active.signal,headers:{'Content-Type':'application/json'},body:identity});const payload=await response.json();if(!response.ok)throw Error(payload.error??'Combined search unavailable');if(!active.signal.aborted){setResult(payload);onMatches(payload.matches);}}catch(cause){if(!active.signal.aborted)setError(cause instanceof Error?cause.message:'Combined search unavailable');}finally{if(!active.signal.aborted)setLoading(false);}}
 return <section className="combined-search"><h2>Find combined matches</h2><p>Every destination’s travel limits + £{minimumPrice.toLocaleString('en-GB')}–£{maximumPrice.toLocaleString('en-GB')} recorded sales.</p><label><input type="checkbox" checked={school.enabled} onChange={e=>setSchool({...school,enabled:e.target.checked})}/> Require a matching school nearby</label>{school.enabled&&<div className="combined-fields"><label>School phase<select value={school.phase} onChange={e=>setSchool({...school,phase:e.target.value})}>{['All','Primary','Secondary','Nursery','Special'].map(p=><option key={p}>{p}</option>)}</select></label><label>Ofsted requirement<select value={school.rating} onChange={e=>setSchool({...school,rating:e.target.value})}><option value="all">Any report</option><optgroup label="Legacy overall grade">{[['1','Outstanding'],['2','Good'],['3','Requires improvement'],['4','Inadequate']].map(([v,l])=><option value={'legacy:'+v} key={v}>{l}</option>)}</optgroup><optgroup label="New report-card grade">{['Exceptional','Strong standard','Expected standard','Needs attention','Urgent improvement'].map(g=><option value={'new:'+g} key={g}>{g}</option>)}</optgroup></select></label>{school.rating.startsWith('new:')&&<label>Inspection category<select value={school.reportArea} onChange={e=>setSchool({...school,reportArea:e.target.value})}>{['Achievement','Curriculum and teaching','Inclusion','Attendance and behaviour','Personal development and wellbeing','Leadership and governance'].map(g=><option key={g}>{g}</option>)}</select></label>}<label>Maximum school walk (minutes)<input type="number" min="1" max="60" value={school.maximumWalkMinutes} onChange={e=>setSchool({...school,maximumWalkMinutes:Number(e.target.value)})}/></label><small>Exact inspection grade; school locations are approximate. Admissions are not checked.</small></div>}<button className="btn primary" disabled={loading&&current} onClick={search}>{loading&&current?'Checking journeys, sales and schools…':'Find combined matches'}</button>{current&&error&&<p role="alert">{error}</p>}{current&&result&&<><p role="status">{result.matches.length} combined matches found.{result.priceFailures+result.routeFailures>0?` Some checks were unavailable (${result.priceFailures} price searches, ${result.routeFailures} routes).`:''}</p>{result.matches.map(match=><button className="combined-match" key={match.id} onClick={()=>onSelect(match)}><strong>{match.name} · £{match.price.toLocaleString('en-GB')}</strong><small>Mean of matching historical sales</small>{match.journeys.map((j,i)=><span key={i}>{j.label}: {j.minutes} min · {j.mode}</span>)}{match.school&&<span>{match.school.name}: {match.school.minutes} min walk</span>}</button>)}{!result.matches.length&&<p>No verified matches in this sample. Try another map point, broader limits or a different school requirement.</p>}<small>{result.note}</small></>}</section>;
}
