"use client";
import {useCallback,useState} from "react";
import {GoogleAreaMap} from "./GoogleAreaMap";
import {DeterministicCriteriaParser} from "@/src/lib/ai/parser";
import {mockCells} from "@/src/lib/data/mockCells";
import {optimise} from "@/src/lib/optimisation/engine";
import {CachedRoutingProvider,MemoryTravelTimeCache} from "@/src/lib/routing/cache";
import {MockRoutingProvider} from "@/src/lib/routing/provider";
import type {LocationScore,OptimisationMode} from "@/src/types/domain";

const prompt="I work in Middleton five days a week. We have a £1 million budget and want somewhere fairly rural with good schools, green space and no more than about 35 minutes to work.";
const money=(n:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0,notation:n>=1e6?"compact":"standard"}).format(n);
const colour=(n:number)=>n>=88?"#7fbd62":n>=84?"#b9d86f":n>=80?"#e2cd74":"#d99564";

export function HeatMapApp(){
 const [mode,setMode]=useState<OptimisationMode>("live"),[inputMode,setInputMode]=useState<"ai"|"manual">("ai"),[text,setText]=useState(prompt),[results,setResults]=useState<LocationScore[]>([]),[focused,setFocused]=useState<string>(),[loading,setLoading]=useState(false),[budget,setBudget]=useState(1e6),[schools,setSchools]=useState(90),[green,setGreen]=useState(90);
 const select=useCallback((id:string)=>setFocused(id),[]);
 async function run(){setLoading(true);try{const criteria=await new DeterministicCriteriaParser().parse(inputMode==="ai"?text:`Middleton five days, 35 minutes, £${budget} budget, schools and green space`);criteria.mode=mode;if(inputMode==="manual"){criteria.property={maximumBudget:budget,hardBudget:false};criteria.lifestyle=criteria.lifestyle.map(p=>p.key==="schools"?{...p,weight:schools}:p.key==="greenSpace"?{...p,weight:green}:p)}setResults(await optimise(criteria,mockCells,new CachedRoutingProvider(new MockRoutingProvider(),new MemoryTravelTimeCache())))}finally{setLoading(false)}}
 if(results.length)return <Results results={results} focused={focused} select={select} edit={()=>setResults([])}/>;
 return <main className="shell"><Nav/><section className="hero"><span className="eyebrow">Area recommendations, made personal</span><h1 className="serif">Where does your life<br/><em>fit best?</em></h1><p className="sub">Balance commute, budget, schools and green space on one geographic suitability map.</p><div className="mode-switch"><button className={mode==="live"?"active":""} onClick={()=>setMode("live")}>Where should I live?</button><button className={mode==="work"?"active":""} onClick={()=>setMode("work")}>Where should I work?</button></div><div className="search-card"><div className="input-tabs"><button className={inputMode==="ai"?"active":""} onClick={()=>setInputMode("ai")}>✦ Describe your ideal area</button><button className={inputMode==="manual"?"active":""} onClick={()=>setInputMode("manual")}>Adjust priorities</button></div>{inputMode==="ai"?<textarea className="prompt" value={text} onChange={e=>setText(e.target.value)} aria-label="Describe your ideal area"/>:<div className="manual"><Field id="destination" label="Main destination"><input id="destination" defaultValue="Middleton"/></Field><Field id="budget" label="Maximum budget"><input id="budget" type="number" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></Field><Weight label="Schools" value={schools} set={setSchools}/><Weight label="Green space" value={green} set={setGreen}/></div>}<div className="prompt-foot"><small>Google Maps-ready · historical area estimates, not listings</small><button className="go" onClick={run} disabled={loading}>{loading?"Building your map…":"Show my heat map"}<span>→</span></button></div></div><p className="demo-note">Scores, routes and historical prices are mock until live data providers are configured.</p></section><section className="proof"><div><b>Google basemap</b>Familiar roads, labels and transport context.</div><div><b>Suitability polygons</b>Area cells remain our own transparent scoring layer.</div><div><b>Provider-independent</b>Routing stays isolated behind a replaceable adapter.</div></section></main>;
}

function Results({results,focused,select,edit}:{results:LocationScore[];focused?:string;select:(id:string)=>void;edit:()=>void}){const active=results.find(r=>r.h3Index===focused)??results[0];return <main className="workspace"><Nav/><section className="result-head"><div><span className="eyebrow">Your suitability heat map</span><h1 className="serif">Best areas for your life</h1></div><button className="btn light" onClick={edit}>Edit priorities</button></section><div className="heat-layout"><section className="heat-map google"><GoogleAreaMap results={results} activeId={active.h3Index} onSelect={select}/><div className="heat-legend"><b>AREA FIT</b><span><i style={{background:"#7fbd62"}}/>Excellent</span><span><i style={{background:"#b9d86f"}}/>Good</span><span><i style={{background:"#e2cd74"}}/>Compromise</span></div><div className="heat-callout"><span className="eyebrow">Selected area</span><h2>{active.town}</h2><b>{active.overallScore}/100 · {money(active.typicalHousePrice)} historical estimate</b><p>Commute {active.destinationResults[0]?.minutes} min · Affordability {active.components.affordability}/100</p></div></section><aside className="area-list"><div className="area-intro"><b>Ranked areas</b><span>Area estimates, not listings.</span></div>{results.slice(0,8).map((r,i)=><button className={`area-card area-button ${active.h3Index===r.h3Index?"selected":""}`} key={r.h3Index} onClick={()=>select(r.h3Index)}><span className="area-rank">{i+1}</span><span className="area-copy"><strong>{r.town}</strong><span className="area-metrics"><span>Commute <b>{r.destinationResults[0]?.minutes} min</b></span><span>Estimate <b>{money(r.typicalHousePrice)}</b></span><span>Affordability <b>{r.components.affordability}</b></span></span><small>{r.positives[0]??r.compromises[0]}</small></span><span className="area-score" style={{background:colour(r.overallScore)}}>{r.overallScore}</span></button>)}</aside></div></main>}
function Field({id,label,children}:{id:string;label:string;children:React.ReactNode}){return <div className="field"><label htmlFor={id}>{label}</label>{children}</div>}
function Weight({label,value,set}:{label:string;value:number;set:(n:number)=>void}){return <div className="range"><div className="range-head"><span>{label}</span><b>{value>80?"High":value>50?"Medium":"Low"}</b></div><input aria-label={`${label} importance`} type="range" value={value} onChange={e=>set(Number(e.target.value))}/></div>}
function Nav(){return <nav className="nav"><div className="brand"><span className="brandmark"/>placewise</div><div className="nav-actions"><button className="btn">How it works</button><button className="btn">My areas</button><button className="btn primary">Sign in</button></div></nav>}
