"use client";
import {useEffect,useState} from 'react';
import type {Map as MapLibreMap,Marker,Popup} from 'maplibre-gl';
import {layerDefinitions,type LayerId,type LayerData,type PointLayer,type ViewBounds} from '@/src/lib/data/layers';

function PointOverlay({map,id,budget,minimumBudget,phase,rating,reportArea}:{map:MapLibreMap;id:PointLayer;budget:number;minimumBudget:number;phase:string;rating:string;reportArea:string}){
  const [bounds,setBounds]=useState<ViewBounds>();const [data,setData]=useState<LayerData>();const [error,setError]=useState<string>();const [loading,setLoading]=useState(true);const [retry,setRetry]=useState(0);
  useEffect(()=>{let timer:ReturnType<typeof setTimeout>;const update=()=>{clearTimeout(timer);timer=setTimeout(()=>{const b=map.getBounds();setLoading(true);setError(undefined);setData(undefined);setBounds({west:+b.getWest().toFixed(4),east:+b.getEast().toFixed(4),south:+b.getSouth().toFixed(4),north:+b.getNorth().toFixed(4)});},400);};update();map.on('moveend',update);return()=>{clearTimeout(timer);map.off('moveend',update);};},[map]);
  useEffect(()=>{if(!bounds)return;const controller=new AbortController();const params=new URLSearchParams({layer:id,...(id==='property'?{minimumPrice:String(minimumBudget),maximumPrice:String(budget)}:{}),...(id==='schools'?{phase,rating,reportArea}:{}),...Object.fromEntries(Object.entries(bounds).map(([k,v])=>[k,String(v)]))});void fetch(`/api/layers?${params}`,{signal:controller.signal}).then(async response=>{const payload=await response.json();if(!response.ok)throw Error(payload.error??'Layer unavailable');if(!controller.signal.aborted)setData(payload);}).catch(cause=>{if(!controller.signal.aborted)setError(cause.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[bounds,id,retry,budget,minimumBudget,phase,rating,reportArea]);
  useEffect(()=>{if(!data)return;let cancelled=false;const markers:Marker[]=[];const popups:Popup[]=[];
    void import('maplibre-gl').then(({Marker,Popup})=>{if(cancelled)return;const definition=layerDefinitions.find(d=>d.id===id)!;
      for(const point of data.points.filter(p=>id!=='schools'||phase==='All'||p.phase===phase)){
        const pin=document.createElement('button');pin.className='layer-pin';pin.type='button';pin.style.background=id==='property'?(point.price!<=budget?'#288352':'#b27315'):definition.colour;pin.textContent=definition.symbol;pin.setAttribute('aria-label',`${definition.label}: ${point.name}`);pin.title=point.name;
        const content=document.createElement('div');content.className='layer-popup';const heading=document.createElement('strong');heading.textContent=point.name;content.append(heading);
        for(const text of point.details){const line=document.createElement('p');line.textContent=text;content.append(line);}
        if(point.url&&/^https:\/\//.test(point.url)){const link=document.createElement('a');link.href=point.url;link.target='_blank';link.rel='noopener noreferrer';link.textContent=id==='schools'?'View Ofsted report':'View source';content.append(link);}
        const popup=new Popup({offset:16,maxWidth:'330px'}).setDOMContent(content);popups.push(popup);
        const marker=new Marker({element:pin}).setLngLat([point.longitude,point.latitude]).setPopup(popup).addTo(map);markers.push(marker);
        pin.addEventListener('click',event=>{event.stopPropagation();popups.forEach(other=>{if(other!==popup)other.remove();});marker.togglePopup();});
      }
    });return()=>{cancelled=true;markers.forEach(m=>m.remove());popups.forEach(p=>p.remove());};
  },[data,map,id,budget,phase]);
  return <div className="layer-status" aria-live="polite">{loading?'Loading this view…':error?<><span>{error}</span> <button onClick={()=>{if(error.includes('Zoom'))map.easeTo({zoom:Math.max(map.getZoom()+1,13)});else {setLoading(true);setError(undefined);setData(undefined);setRetry(n=>n+1);}}}>{error.includes('Zoom')?'Zoom in':'Retry'}</button></>:data?<><span>{data.points.filter(p=>id!=='schools'||phase==='All'||p.phase===phase).length} pins. {data.note}</span><a href={data.sourceUrl} target="_blank" rel="noreferrer">{data.source}</a></>:null}</div>;
}
function FloodOverlay({map,kind}:{map:MapLibreMap;kind:'river'|'surface'}){
  const [zoom,setZoom]=useState(map.getZoom());const [error,setError]=useState(false);const [retry,setRetry]=useState(0);
  useEffect(()=>{const id=`flood-${kind}`;const update=()=>setZoom(map.getZoom());const fail=(event:unknown)=>{if((event as {sourceId?:string}).sourceId===id)setError(true);};
    map.addSource(id,{type:'raster',tiles:[`${window.location.origin}/api/flood/${kind}?bbox={bbox-epsg-3857}`],tileSize:256,minzoom:14,attribution:'© Environment Agency copyright and database right 2025 · OGL'});map.addLayer({id,type:'raster',source:id,paint:{'raster-opacity':0.65}});map.on('zoomend',update);map.on('error',fail);return()=>{map.off('zoomend',update);map.off('error',fail);if(map.getLayer(id))map.removeLayer(id);if(map.getSource(id))map.removeSource(id);};
  },[map,kind,retry]);
  const service=kind==='river'?'nafra2-risk-of-flooding-from-rivers-and-sea':'nafra2-risk-of-flooding-from-surface-water';const layer=kind==='river'?'rofrs_4band':'rofsw';
  return <div className="layer-status">England · annual flood likelihood; area-level guidance. {zoom<14&&<button onClick={()=>map.easeTo({zoom:14})}>Zoom in to see flood detail</button>}{error&&<span role="alert">Flood tiles unavailable. <button onClick={()=>{setError(false);setRetry(n=>n+1);}}>Retry</button></span>}<a href={`https://environment.data.gov.uk/spatialdata/${service}/wms?SERVICE=WMS&REQUEST=GetLegendGraphic&VERSION=1.1.1&FORMAT=image/png&LAYER=${layer}`} target="_blank" rel="noreferrer">View official colour legend</a><a href="https://www.gov.uk/check-long-term-flood-risk" target="_blank" rel="noreferrer">Environment Agency · check a property’s flood risk</a></div>;
}
export function MapLayers({map,budget,minimumBudget}:{map:MapLibreMap|null;budget:number;minimumBudget:number}){
  const [rating,setRating]=useState('all');const [reportArea,setReportArea]=useState('Achievement');
  const [enabled,setEnabled]=useState<LayerId[]>([]);const [phase,setPhase]=useState('All');
  const toggle=(id:LayerId,checked:boolean)=>{setEnabled(old=>checked?[...old,id]:old.filter(value=>value!==id));};
  return <details className="map-layers"><summary>Map layers <span>{enabled.length?`${enabled.length} on`:'Explore'}</span></summary><div className="layer-options"><p>Combine layers. Pan the map to refresh local data.</p>{layerDefinitions.map(layer=><div className="layer-row" key={layer.id}><label><input type="checkbox" checked={enabled.includes(layer.id)} onChange={e=>toggle(layer.id,e.target.checked)}/><i style={{background:layer.colour}}/>{layer.label}</label>{enabled.includes(layer.id)&&<>{layer.id==='property'&&<p className="layer-status">House-price range: £{minimumBudget.toLocaleString('en-GB')}–£{budget.toLocaleString('en-GB')}. Change it with Edit priorities.</p>}{layer.id==='schools'&&<><label className="school-filter">School phase<select aria-label="School phase" value={phase} onChange={e=>setPhase(e.target.value)}>{['All','Primary','Secondary','Nursery','Special','Pupil referral unit'].map(p=><option key={p}>{p}</option>)}</select></label><label className="school-filter">Ofsted grade<select aria-label="Ofsted grade" value={rating} onChange={e=>setRating(e.target.value)}><option value="all">All reports</option><optgroup label="Legacy overall grade">{[['1','Outstanding'],['2','Good'],['3','Requires improvement'],['4','Inadequate']].map(([value,label])=><option key={value} value={'legacy:'+value}>{label}</option>)}</optgroup><optgroup label="New report-card grade">{['Exceptional','Strong standard','Expected standard','Needs attention','Urgent improvement'].map(grade=><option key={grade} value={'new:'+grade}>{grade}</option>)}</optgroup></select></label>{rating.startsWith('new:')&&<label className="school-filter">Report area<select aria-label="Ofsted report area" value={reportArea} onChange={e=>setReportArea(e.target.value)}>{['Achievement','Curriculum and teaching','Inclusion','Attendance and behaviour','Personal development and wellbeing','Leadership and governance','Early years (where applicable)','Post-16 provision (where applicable)'].map(area=><option key={area}>{area}</option>)}</select></label>}<p className="layer-status">Matches the selected grade exactly in the latest report. Older overall grades and newer report-card grades are separate.</p></>}{map?(layer.id==='river'||layer.id==='surface'?<FloodOverlay map={map} kind={layer.id}/>:<PointOverlay key={layer.id==='schools'?`${phase}:${rating}:${reportArea}`:layer.id} map={map} id={layer.id} budget={budget} minimumBudget={minimumBudget} phase={phase} rating={rating} reportArea={reportArea}/>):<small>Preparing map…</small>}</>}</div>)}</div></details>;
}
