import type { TransportMode } from "@/src/types/domain";
import type { RoutingOptions,RoutingProvider,TravelTimeResult } from "./provider";
import { getPlacewiseClient } from "@/src/lib/supabase/server";
export interface TravelTimeCache { get(key:string):Promise<(TravelTimeResult&{expiresAt:number})|null>; set(key:string,value:TravelTimeResult&{expiresAt:number}):Promise<void> }
export class MemoryTravelTimeCache implements TravelTimeCache { private rows=new Map<string,TravelTimeResult&{expiresAt:number}>();async get(k:string){return this.rows.get(k)??null}async set(k:string,v:TravelTimeResult&{expiresAt:number}){this.rows.set(k,v)} }
export class SupabaseTravelTimeCache implements TravelTimeCache {
 async get(key:string){const [origin_h3,destination_h3,transport_mode,time_profile]=key.split(":");const {data,error}=await getPlacewiseClient().from("travel_time_cache").select("minutes,distance_km,source,expires_at").match({origin_h3,destination_h3,transport_mode,time_profile}).maybeSingle();if(error)throw new Error(error.message);return data&&data.distance_km!==null?{minutes:data.minutes,distanceKm:Number(data.distance_km),source:data.source,expiresAt:new Date(data.expires_at).getTime()}:null}
 async set(key:string,value:TravelTimeResult&{expiresAt:number}){const [origin_h3,destination_h3,transport_mode,time_profile]=key.split(":");const {error}=await getPlacewiseClient().from("travel_time_cache").upsert({origin_h3,destination_h3,transport_mode,time_profile,minutes:value.minutes,distance_km:value.distanceKm,source:value.source,calculated_at:new Date().toISOString(),expires_at:new Date(value.expiresAt).toISOString()},{onConflict:"origin_h3,destination_h3,transport_mode,time_profile"});if(error)throw new Error(error.message)}
}
export class CachedRoutingProvider { constructor(private provider:RoutingProvider,private cache:TravelTimeCache){} async get(originH3:string,destinationH3:string,origin:{latitude:number;longitude:number},destination:{latitude:number;longitude:number},transportMode:TransportMode,timeProfile="weekday",departureTime?:string){if(transportMode==="transit"||transportMode==="mixed"||transportMode==="any")return this.provider.getTravelTime(origin,destination,{transportMode,timeProfile,departureTime});const key=[originH3,destinationH3,transportMode,timeProfile].join(":");const hit=await this.cache.get(key);if(hit&&hit.expiresAt>Date.now())return hit;const value=await this.provider.getTravelTime(origin,destination,{transportMode,timeProfile} as RoutingOptions);await this.cache.set(key,{...value,expiresAt:Date.now()+86400000*30});return value;} }
